iommu: arm-smmu: Remove duplicate driver registration
The arm-smmu driver is being registered twice, causing the following
error on boot:
    Error: Driver 'arm-smmu' is already registered, aborting...

Remove the duplicate subsys_initcall() to fix this.